# opt-in to Travis new container-based infrastructure
sudo: false

cache:
  directories:
  - $HOME/.npm
  - node_modules

language: javascript

addons:
  apt:
    packages:
    - libfontconfig1
    - fontconfig
    - libfontconfig1-dev
    - libfreetype6-dev

install:
  - npm install
script:
  - grunt test

after_failure:
  - dmesg | tail -100

notifications:
  hipchat:
    rooms:
      secure: "EEaRwfUUBj1phN/+8C3mbZARgSy3QWkx/ppQy/aBtydWpT82Mx3fhqOTKDpS3onEjioMqSOKzOGtQuZ1KP1agy11WDTFkwAhg9MMPzdc3J0gRaxhI6FyfZ9emWYmzM6GxGMtJZM1hOvenPp5QDQ7POyhCuQUW3+Utv2vQM3PkBg="
